### ISSUE TITLE
Chat delay

### ISSUE THREAD

**Issue by WobbleBaby** [vyneer/orvods-go#25]
Chat is 5 hours delayed (at least when the vod is split up) 

When the chat catches up:
https://vyneer.me/vods/?ay=lmulS5JDS9o1670500860000&start=2022-12-08T12:01:00.000Z&end=2022-12-09T00:01:00.000Z&provider=vyneer&t=18018

Used this service twice (different days/vods) but both times the vod was split and both times the chat was delayed HOURS.

**Comment by vyneer** [comment]
Fixed in aca8162

**Comment by WobbleBaby** [comment]
How am i supposed to adjust 5h without some kind of search function for like a keyword "LIVE" or "angelthump". Is this issue only for when the VOD is split?

**Comment by vyneer** [comment]
I'm not sure what you're asking, I fixed the issue.

The problem was with the timezone mismatch between the vodstiny server and the timestamps served from it, so I added a manual offset.
