### ISSUE TITLE
Chat stops scrolling randomly/when moving too fast

### ISSUE THREAD

**Issue by vyneer** [vyneer/orvods-go#3]

**Comment by vyneer** [comment]
Removed the 'only scroll when at the bottom' feature in https://github.com/vyneer/orvods-go/commit/6aff3bc410007838088adf927ac92f945b3d2d4d until I figure out how to fix this/do this properly.

**Comment by MatthewBerkvens** [comment]
This should fix it https://github.com/vyneer/orvods-go/pull/13

**Comment by vyneer** [comment]
Looks like it's fixed, tyvm @MatthewBerkvens <3
