### ISSUE TITLE
Toggle chat visibility

### ISSUE THREAD

**Issue by excd** [vyneer/orvods-go#31]
As far as I can tell there's no feature to toggle the chat visibility. I don't really read the off-screen chat and would prefer to be able to hide it without having to go full screen.

**Comment by vyneer** [comment]
I'm not sure I understand, is there a reason you'd wanna hide chat instead of just watching on the original platform?

**Comment by Excd** [comment]
I just like the convenience of this site, but other than that not really I suppose. If it's too much trouble then don't worry about, I'm not sure how many people other than me would want this feature I guess lol.

**Comment by LMWdgg** [comment]
Given the recent unavailability of YT vods, I think some folks would appreciate a view without the forced sidebar chat. At least a button to toggle.

**Comment by vyneer** [comment]
Added in https://github.com/vyneer/orvods-go/commit/262106a359c477902a395cc1ad9879936c390144 WEOW
